version: 2
before:
  hooks:
    - go mod download
builds:
  - id: kubectl-flame
    main: ./cli/main.go
    binary: kubectl-flame
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
      - ppc64le
    goarm: [6, 7]
    ldflags: |
      -X github.com/adesaegher/kubectl-flame/cli/cmd/version.semver={{ .Tag }}
      -X github.com/adesaegher/kubectl-flame/cli/cmd/version.date={{ .Date }}
      -X github.com/adesaegher/kubectl-flame/cli/cmd/version.commit={{ .Commit }}
archives:
  - id: kubectl-flame-archive
    name_template: |
      kubectl-flame_{{ .Tag }}_{{ .Os }}_{{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    builds:
      - kubectl-flame
    format_overrides:
      - goos: windows
        format: zip
    files: ["LICENSE"]
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
