name: Release
on:
  push:
    tags:
    - 'v*.*.*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set env
      id: vars
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    # - name: Build JVM Docker Image
    #   uses: docker/build-push-action@v6
    #   with:
    #     context: "{{defaultContext}}:agent/docker/jvm"
    #     push: true
    #     tags: desaegher/kubectl-flame:${{ steps.vars.outputs.tag }}-jvm
    - name: Build BPF Docker Image
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}:."
        file: agent/docker/bpf/Dockerfile
        push: true
        tags: desaegher/kubectl-flame:${{ steps.vars.outputs.tag }}-bpf
    - name: Build Python Docker Image
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}:agent/docker/python"
        push: true
        tags: desaegher/kubectl-flame:${{ steps.vars.outputs.tag }}-python
    - name: Build Ruby Docker Image
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}:agent/docker/ruby"
        push: true
        tags: desaegher/kubectl-flame:${{ steps.vars.outputs.tag }}-ruby
    - name: Build perf Docker Image
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}:agent/docker/perf"
        push: true
        tags: desaegher/kubectl-flame:${{ steps.vars.outputs.tag }}-perf
    - name: Build php Docker Image
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}:agent/docker/php"
        push: true
        tags: desaegher/kubectl-flame:${{ steps.vars.outputs.tag }}-php
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - name: GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
    - name: Update new version in krew-index
      uses: rajatjindal/krew-release-bot@v0.0.38
